import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './header/header'
import Footer from "./footer/footer";
import Style from "./style/style";
import Page from "./page";
import Blog from "./blog/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
